name: Changelog Validation

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate changelogs
        uses: Kong/gateway-changelog@591a18e5bad42926a0c78cb1f757a5572b9da20c
        with:
          files: changelog/unreleased/*/*.yml
